/* eslint-disable */
// Generated by component library do not modify
const ComponentsContent = require('./components/content.jsx');
const ComponentsCreate = require('./components/create.jsx');
const ComponentsItem = require('./components/item.jsx');

function dispatchEvent(data) {
  if (typeof window !== 'undefined')
    document.dispatchEvent(new BluekitEvent('functionTriggered', data));
  else
    console.log('Bluekit received function triggered', data)
}
module.exports = {
  ComponentsContent: {
    name: 'ComponentsContent',
    menu: 'Components Content',
    file: './components/content.jsx',
    component: ComponentsContent,
    componentName: 'content',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
  ComponentsCreate: {
    name: 'ComponentsCreate',
    menu: 'Components Create',
    file: './components/create.jsx',
    component: ComponentsCreate,
    componentName: 'create',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
  ComponentsItem: {
    name: 'ComponentsItem',
    menu: 'Components Item',
    file: './components/item.jsx',
    component: ComponentsItem,
    componentName: 'item',
    description: '',
    customProps: {},
    propsDefinition: {},
    simpleProps: {},
    fullProps: {}
  },
}
